repos:
  - repo: https://github.com/7Last/docs/
    hooks:
      - id: add-links-to-glossary-words
        name: add-links-to-glossary-words
        entry: python3 ./scripts/check_glossary.py
        description: "Add links to glossary words"
ci:
  autofix_commit_msg: "[pre-commit.ci] auto added links to glossary words"
  autoupdate_commit_msg: "[pre-commit.ci] auto added links to glossary words"
  autoupdate_branch: 'develop'