name: Deploy docs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  update-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.0'

      - name: Configure SSH and clone
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "7last.swe@gmail.com"
          git config --global user.name "bot"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
         repository: 7Last/7Last.github.io
         ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
         path: .
         ref: main

      - name: Fetch docs submodule
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: npm install

      - name: Run deploy command
        run: npm run deploy

      - name: cat src/static/docs.json
        run: cat src/static/docs.json


      # - name: Push updates on main
      #   run: |
      #     git add .
      #     git commit -m "[BOT] Update docs"
      #     git push origin main
