name: Deploy docs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.0'

      - name: Configure SSH and clone
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "7last.swe@gmail.com"
          git config --global user.name "bot"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         repository: 7Last/7Last.github.io
         ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
         path: .
         ref: main

      - name: Fetch docs submodule
        run: git submodule update --remote --merge

      - name: Tree
        run: tree .

      - name: Install requirements
        run: pip3 install -r ./scripts/requirements.txt

      - name: Generate docs
        run: python3 ./scripts/generate_docs.py


      - name: Check for changes
        run: |
          git diff --exit-code || exit 0
          git diff --cached --exit-code || exit 0
          echo "No changes to the output on this push; exiting."
          exit 0

      - name: Push updates on main
        env:
          MSG: ${{ github.event.head_commit.message }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          git add .
          git commit -m "[BOT] \"$MSG\" by $AUTHOR"
          git push origin main

      - name: Install dependencies
        run: npm install

      - name: Run deploy command
        run: USE_SSH=true npm run deploy
