name: Pre merge checks

on:
  # pull_request:
  #   branches: [develop]
  #   types: [opened, reopened, review_requested, edited, synchronize]
  push:
    branches: [ "feature/aspell" ]

  workflow_dispatch:

jobs:
  aspell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install aspell and Italian dictionary
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-it aspell-en

      - name: List latex files
        run: |
          files=$(find . -name '*.tex')
          output_file="misspelled_words.txt"
          > "$output_file"  # Clear the output file if it exists

          for file in $files; do
              aspell pipe list -t --lang=it_IT --personal=.wordlist.txt < "$file" |
                  grep '[a-zA-Z]\+ [0-9]\+ [0-9]\+' -oh |
                  grep '[a-zA-Z]\+' -o |
                  aspell pipe list -t --lang=en_US |
                  grep '[a-zA-Z]\+ [0-9]\+ [0-9]\+' -oh |
                  grep '[a-zA-Z]\+' -o |
                  sort -u >> "$output_file"
          done

          # Sort and print unique words
          sort "$output_file" | uniq
