name: Pre merge checks

on:
  # pull_request:
  #   branches: [develop]
  #   types: [opened, reopened, review_requested, edited, synchronize]
  push:
    branches: [ "feature/aspell" ]

  workflow_dispatch:

jobs:
  aspell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install aspell and Italian dictionary
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-it

      - name: List latex files
        run: |
          files=$(find . -name '*.tex')
          for file in $files; do
            echo "Checking $file"
            aspell list -t --lang=it_IT $file
          done
