name: Pre merge checks

on:
  # pull_request:
  #   branches: [develop]
  #   types: [opened, reopened, review_requested, edited, synchronize]
  push:
    branches: [ "feature/aspell" ]

  workflow_dispatch:

jobs:
  aspell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub Spellcheck
        uses: igsekor/pyspelling-any@v1.0.4
            
