name: Pre merge checks

on:
  # pull_request:
  #   branches: [develop]
  #   types: [opened, reopened, review_requested, edited, synchronize]
  push:
    branches: [ "feature/aspell" ]

  workflow_dispatch:

jobs:
  aspell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install aspell and Italian dictionary
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-it

      - name: List latex files
        run: |
          files=$(find . -name '*.tex')
          for file in $files; do
             aspell pipe list -t --lang=it_IT <"$file" |
                 grep '[a-zA-Z]\+ [0-9]\+ [0-9]\+' -oh | \
                 grep '[a-zA-Z]\+' -o | \
                 aspell pipe list -t --lang=en_US |
                 grep '[a-zA-Z]\+ [0-9]\+ [0-9]\+' -oh | \
                 grep '[a-zA-Z]\+' -o | \
              while read word; do grep -on "\<$word\>" $file; done
          done
