name: Pre merge checks

on:
  # pull_request:
  #   branches: [develop]
  #   types: [opened, reopened, review_requested, edited, synchronize]
  push:
    branches: [ "feature/aspell" ]

  workflow_dispatch:

jobs:
  aspell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install aspell and Italian dictionary
        run: |
          apt-get update
          apt-get install -y aspell aspell-it

      - name: Find and check LaTeX files
        run: |
          # Find all .tex files and check spelling
          find . -type f -name "*.tex" -exec aspell --lang=it --mode=tex check {} \;
            
